import { mountChat, stopChat } from './chat-reliable.js';
import { setBootState, showBootError } from './boot-state.js';
import { sb } from './supabase-client.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'), toastBox=$('#toast');
const st={session:null,profile:null,view:'dashboard',subjects:[],conv:null,channel:null};
const titles={dashboard:'Գլխավոր',schedule:'Դասացուցակ',homework:'Տնային աշխատանքներ',announcements:'Հայտարարություններ',board:'Դասարանի տախտակ',chat:'Չատ',polls:'Հարցումներ',files:'Ֆայլեր',classmates:'Դասընկերներ',notifications:'Ծանուցումներ',profile:'Իմ պրոֆիլը',admin:'Admin',superadmin:'Super Admin'};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('hy-AM',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const initials=p=>`${p?.first_name?.[0]||''}${p?.last_name?.[0]||''}`||'Դ';
const roleName=r=>({STUDENT:'Աշակերտ',ADMIN:'Admin',SUPER_ADMIN:'Super Admin'}[r]||r);
const admin=()=>['ADMIN','SUPER_ADMIN'].includes(st.profile?.role), superAdmin=()=>st.profile?.role==='SUPER_ADMIN';
function toast(t,k=''){const e=document.createElement('div');e.className=`toast ${k}`;e.textContent=t;toastBox.append(e);setTimeout(()=>e.remove(),4200)}
function theme(){const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('portal-theme',n)}
document.documentElement.dataset.theme=localStorage.getItem('portal-theme')||'light';
function busy(b,on){if(!b)return;if(on){b.dataset.t=b.textContent;b.disabled=true;b.textContent='Սպասեք…'}else{b.disabled=false;b.textContent=b.dataset.t||b.textContent}}
function pending(){try{return JSON.parse(localStorage.getItem('portal-pending')||'null')}catch{return null}}
function savePending(x){localStorage.setItem('portal-pending',JSON.stringify(x))} function clearPending(){localStorage.removeItem('portal-pending')}

let sessionRevision=0, identityJob=null, recovering=false, chatRevision=0;
async function boot(){
  setBootState('AUTH_CHECK');
  sb.auth.onAuthStateChange((event,session)=>{
    const changed=st.session?.user?.id!==session?.user?.id;
    if(event==='PASSWORD_RECOVERY')recovering=true;
    if(event==='SIGNED_OUT')recovering=false;
    st.session=session;
    if(changed||event==='SIGNED_OUT'||event==='PASSWORD_RECOVERY')sessionRevision++;
    const revision=sessionRevision;
    // Supabase invokes this callback under its auth lock. Never await RPC here.
    setTimeout(()=>{
      if(revision!==sessionRevision)return;
      if(!session){st.profile=null;st.subjects=[];st.conv=null;cleanup();closeModal();auth();}
      else if(recovering)resetPassword();
      else if(changed||!st.profile)identity().catch(showBootError);
      else if(event==='TOKEN_REFRESHED')identity(true).catch(showBootError);
    },0);
  });
  const revision=sessionRevision;
  const {data,error}=await sb.auth.getSession();
  if(revision!==sessionRevision)return;
  if(error)throw error;
  st.session=data.session;
  if(recovering&&st.session)resetPassword();else if(st.session)await identity();else auth();
}
async function identity(preserve=false){
  const revision=sessionRevision,userId=st.session?.user?.id;
  if(!userId)return auth();
  if(recovering)return resetPassword();
  if(identityJob?.revision===revision)return identityJob.promise;
  const current=()=>revision===sessionRevision&&st.session?.user?.id===userId;
  const job={revision};
  identityJob=job;
  job.promise=(async()=>{
    const {data,error}=await sb.rpc('get_my_profile');
    if(!current())return;
    if(error)return fatal();
    let next=Array.isArray(data)?data[0]:data;
    if(!next){
      const p=pending();
      if(p&&await claim(p)){
        if(!current())return;
        const result=await sb.rpc('get_my_profile');
        if(!current())return;
        if(result.error)return fatal();
        next=Array.isArray(result.data)?result.data[0]:result.data;
      }
      if(!next){st.profile=null;return completeProfile();}
    }
    if(!next.is_active){st.profile=null;cleanup();await sb.auth.signOut({scope:'local'});return blocked();}
    const unchanged=st.profile?.id===next.id&&st.profile?.role===next.role;
    st.profile=next;
    if(preserve&&unchanged&&app.querySelector('.portal'))return;
    const r=await sb.from('subjects').select('*').order('name');
    if(!current())return;
    if(r.error)return fatal();
    st.subjects=r.data||[];
    if(!items().some(([key])=>key===st.view))st.view='dashboard';
    portal();
  })().finally(()=>{if(identityJob===job)identityJob=null;});
  return job.promise;
}
window.addEventListener('focus',()=>{if(st.session&&st.profile)identity(true).catch(showBootError);});
setInterval(()=>{if(!document.hidden&&st.session&&st.profile)identity(true).catch(showBootError);},60000);
async function claim(p){if(!p?.first||!p?.last||!p?.username||!p?.invite)return false;const {data,error}=await sb.rpc('claim_class_profile',{p_first_name:p.first.trim(),p_last_name:p.last.trim(),p_username:p.username.trim(),p_invite_code:p.invite.trim()});if(error||data!==true)return false;clearPending();return true}

function auth(tab='login'){cleanup();app.innerHTML=`<div class="auth"><section class="hero"><div class="logo">Դ</div><h1>Մեր դասարանը՝ մեկ տեղում</h1><p>Փակ պորտալ՝ դասացուցակի, տնայինների, չատի, ֆայլերի, հայտարարությունների և հարցումների համար։</p><div class="hero-grid"><div><b>🔒 Փակ մուտք</b><br>Միայն մեր դասարանի անդամների համար</div><div><b>💬 Արագ չատ</b><br>Դասարան և անձնական զրույցներ</div><div><b>📚 Դասեր</b><br>Դասացուցակ և տնայիններ</div><div><b>🛡️ Անվտանգություն</b><br>Յուրաքանչյուրն ունի իր իրավունքները</div></div></section><section class="auth-side"><div class="auth-card"><div class="tabs"><button class="tab ${tab==='login'?'active':''}" data-tab="login">Մուտք</button><button class="tab ${tab==='register'?'active':''}" data-tab="register">Գրանցում</button></div><div id="auth-body"></div></div></section></div>`;$$('[data-tab]').forEach(b=>b.onclick=()=>auth(b.dataset.tab));tab==='login'?loginForm():registerForm();setBootState('LOGIN')}
function loginForm(){
  $('#auth-body').innerHTML=`<h2>Բարի վերադարձ 👋</h2><p class="muted">Մուտք գործիր 9Ա դասարանի փակ պորտալ։</p><form id="login"><div class="field"><label for="login-email">Էլ. փոստ</label><input id="login-email" name="email" type="email" autocomplete="email" required></div><div class="field"><label for="login-password">Գաղտնաբառ</label><input id="login-password" name="password" type="password" autocomplete="current-password" required></div><button class="btn primary wide">Մուտք գործել</button></form><button id="forgot-password" class="btn wide" style="margin-top:9px">Մոռացե՞լ ես գաղտնաբառը</button><div class="divider">կամ</div><button id="glogin" class="btn wide">G · Google</button>`;
  $('#login').onsubmit=async e=>{
    e.preventDefault();const b=e.submitter,f=new FormData(e.currentTarget);busy(b,1);
    try{const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)toast('Մուտքը չհաջողվեց։ Ստուգիր էլ. փոստը և գաղտնաբառը։','err')}
    catch{toast('Կապը չի պատասխանել։ Փորձիր նորից։','err')}
    finally{busy(b,0)}
  };
  $('#glogin').onclick=()=>google(false);
  $('#forgot-password').onclick=recoverEmail;
}
function recoverEmail(){
  $('#auth-body').innerHTML=`<h2>Վերականգնել գաղտնաբառը</h2><form id="recover-email"><div class="field"><label for="recovery-email">Էլ. փոստ</label><input id="recovery-email" name="email" type="email" autocomplete="email" required></div><button class="btn primary wide">Ուղարկել վերականգնման հղումը</button></form><button id="back-login" class="btn wide" style="margin-top:9px">Վերադառնալ մուտքին</button>`;
  $('#back-login').onclick=loginForm;
  $('#recover-email').onsubmit=async e=>{
    e.preventDefault();const b=e.submitter,email=new FormData(e.currentTarget).get('email');busy(b,1);
    try{
      const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});
      if(error)throw error;
      toast('Եթե այս հասցեով հաշիվ կա, վերականգնման հղումը կստանաս էլ. փոստով։','ok');
    }catch{toast('Հղումը չուղարկվեց։ Փորձիր մի փոքր ուշ։','err')}
    finally{busy(b,0)}
  };
}
function resetPassword(){
  cleanup();closeModal();
  if($('#reset-password'))return;
  app.innerHTML=`<div class="auth-side" style="min-height:100vh"><div class="auth-card"><h2>Նոր գաղտնաբառ</h2><form id="reset-password"><div class="field"><label for="new-password">Գաղտնաբառ</label><input id="new-password" name="password" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label for="confirm-password">Կրկնիր գաղտնաբառը</label><input id="confirm-password" name="confirm" type="password" minlength="8" autocomplete="new-password" required></div><button class="btn primary wide">Պահպանել</button></form><button id="cancel-reset" class="btn wide" style="margin-top:9px">Չեղարկել</button></div></div>`;
  setBootState('LOGIN');
  $('#cancel-reset').onclick=()=>sb.auth.signOut({scope:'local'});
  $('#reset-password').onsubmit=async e=>{
    e.preventDefault();const b=e.submitter,f=new FormData(e.currentTarget);
    if(f.get('password')!==f.get('confirm'))return toast('Գաղտնաբառերը չեն համընկնում։','err');
    busy(b,1);
    try{
      const {error}=await sb.auth.updateUser({password:f.get('password')});if(error)throw error;
      recovering=false;await sb.auth.signOut({scope:'local'});auth();
      toast('Գաղտնաբառը փոխվեց։ Մուտք գործիր նոր գաղտնաբառով։','ok');
    }catch{toast('Գաղտնաբառը չփոխվեց։ Նոր հղում խնդրիր և փորձիր կրկին։','err')}
    finally{busy(b,0)}
  };
}
function registerForm(){$('#auth-body').innerHTML=`<h2>Գրանցվել դասարանում</h2><p class="muted">Գրանցումը հնարավոր է միայն գործող invite code-ով։</p><form id="reg"><div class="row2"><div class="field"><label>Անուն</label><input name="first" required></div><div class="field"><label>Ազգանուն</label><input name="last" required></div></div><div class="field"><label>Username</label><input name="username" pattern="[A-Za-z0-9_.-]+" minlength="3" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Գաղտնաբառ</label><input name="password" type="password" minlength="8" required></div><div class="field"><label>Invite code</label><input name="invite" minlength="8" required></div><button class="btn primary wide">Ստեղծել հաշիվ</button></form><div class="divider">կամ</div><button id="greg" class="btn wide">G · Գրանցվել Google-ով</button>`;$('#reg').onsubmit=register;$('#greg').onclick=()=>google(true)}
async function register(e){e.preventDefault();const b=e.submitter, f=new FormData(e.currentTarget), p={first:f.get('first'),last:f.get('last'),username:f.get('username'),invite:f.get('invite')};busy(b,1);const v=await sb.rpc('validate_class_invite',{p_code:p.invite});if(v.error||v.data!==true){busy(b,0);return toast('Invite code-ը սխալ է կամ այլևս չի գործում։','err')}savePending(p);const r=await sb.auth.signUp({email:f.get('email'),password:f.get('password'),options:{emailRedirectTo:`${location.origin}${location.pathname}`}});busy(b,0);if(r.error)return toast(r.error.message,'err');if(r.data.session)return;toast('Հաշիվը ստեղծվել է։ Եթե email հաստատումը միացված է՝ բացիր նամակը և վերադարձիր այստեղ։','ok');auth('login')}
async function google(reg){if(reg){const f=$('#reg');if(!f.reportValidity())return;const d=new FormData(f),p={first:d.get('first'),last:d.get('last'),username:d.get('username'),invite:d.get('invite')};const v=await sb.rpc('validate_class_invite',{p_code:p.invite});if(v.error||v.data!==true)return toast('Invite code-ը սխալ է։','err');savePending(p)}const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}${location.pathname}`}});if(r.error)toast('Google մուտքը դեռ կարգավորված չէ․ '+r.error.message,'err')}
function completeProfile(){cleanup();app.innerHTML=`<div class="auth-side" style="min-height:100vh"><div class="auth-card"><div class="logo">Դ</div><h2>Ավարտիր պրոֆիլը</h2><p class="muted">Auth հաշիվը կա, բայց դասարանի պրոֆիլը դեռ ակտիվացված չէ։</p><form id="complete"><div class="row2"><div class="field"><label>Անուն</label><input name="first" required></div><div class="field"><label>Ազգանուն</label><input name="last" required></div></div><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Invite code</label><input name="invite" minlength="8" required></div><button class="btn primary wide">Ակտիվացնել</button></form><button id="out" class="btn wide" style="margin-top:9px">Դուրս գալ</button></div></div>`;$('#complete').onsubmit=async e=>{e.preventDefault();const b=e.submitter,d=new FormData(e.currentTarget);busy(b,1);const ok=await claim({first:d.get('first'),last:d.get('last'),username:d.get('username'),invite:d.get('invite')});busy(b,0);ok?identity():toast('Տվյալները կամ invite code-ը սխալ են։','err')};$('#out').onclick=()=>sb.auth.signOut();setBootState('LOGIN')}
function blocked(){app.innerHTML=`<div class="auth-side" style="min-height:100vh"><div class="auth-card"><h2>Հաշիվը արգելափակված է</h2><p class="muted">Դիմիր Super Admin-ին։</p><button id="out" class="btn wide">Դուրս գալ</button></div></div>`;$('#out').onclick=()=>sb.auth.signOut();setBootState('LOGIN')}
function fatal(){cleanup();st.profile=null;showBootError()}

function items(){const a=[['dashboard','⌂','Գլխավոր'],['schedule','▦','Դասացուցակ'],['homework','✓','Տնայիններ'],['announcements','◉','Հայտարարություններ'],['board','▤','Տախտակ'],['chat','✦','Չատ'],['polls','◌','Հարցումներ'],['files','▣','Ֆայլեր'],['classmates','♙','Դասընկերներ'],['notifications','●','Ծանուցումներ'],['profile','◎','Պրոֆիլ']];if(admin())a.push(['admin','⚙','Admin']);if(superAdmin())a.push(['superadmin','◆','Super Admin']);return a}
function portal(){const p=st.profile;app.innerHTML=`<div class="portal"><aside class="sidebar"><div class="brand"><div class="logo">Դ</div><div><b>Դասարան</b><div class="small muted">9Ա · Փակ պորտալ</div></div></div><nav class="nav">${items().map(([k,i,l])=>`<button data-nav="${k}" class="${st.view===k?'active':''}">${i} ${l}</button>`).join('')}</nav><div class="side-foot"><div class="user"><div class="avatar">${esc(initials(p))}</div><div><b>${esc(p.first_name)} ${esc(p.last_name)}</b><div class="small muted">${esc(roleName(p.role))}</div></div></div><button id="theme" class="btn">◐ Թեմա</button><button id="logout" class="btn">Դուրս գալ</button></div></aside><main class="main"><div class="top"><div><div class="small muted">Դասարանի փակ պորտալ</div><h1 id="vt">${esc(titles[st.view])}</h1></div><div class="actions"><button id="refresh" class="btn">↻</button><button id="theme2" class="btn">◐</button></div></div><section id="view"></section></main><nav class="mobile">${[['dashboard','⌂','Գլխավոր'],['schedule','▦','Դասեր'],['homework','✓','Տնային'],['chat','✦','Չատ'],['profile','◎','Պրոֆիլ']].map(([k,i,l])=>`<button data-nav="${k}" class="${st.view===k?'active':''}">${i}<br>${l}</button>`).join('')}</nav></div>`;$$('[data-nav]').forEach(b=>b.onclick=()=>{st.view=b.dataset.nav;portal()});$('#logout').onclick=()=>sb.auth.signOut();$('#theme').onclick=theme;$('#theme2').onclick=theme;$('#refresh').onclick=renderView;renderView();setBootState('PORTAL')}
async function renderView(){cleanup();$('#vt').textContent=titles[st.view]||'Դասարան';const v=$('#view');v.innerHTML='<div class="card">Բեռնվում է…</div>';const event=new CustomEvent('portal:render-view',{cancelable:true,detail:{view:st.view}});if(!window.dispatchEvent(event))return;try{await ({dashboard,schedule,homework,announcements,board,chat,polls,files,classmates,notifications,profile,admin:adminView,superadmin:superView}[st.view]||dashboard)(v)}catch(e){v.innerHTML=`<div class="card"><h3>Չհաջողվեց բեռնել</h3><p class="muted">${esc(e.message||e)}</p></div>`}}

async function dashboard(v){const [h,a,n,e]=await Promise.all([sb.from('homework').select('id,title,due_at,subject:subjects(name,short_name)').gte('due_at',new Date().toISOString()).order('due_at').limit(5),sb.from('announcements').select('*').order('is_pinned',{ascending:false}).order('created_at',{ascending:false}).limit(4),sb.from('notifications').select('id').is('read_at',null),sb.from('events').select('id,title,starts_at').gte('starts_at',new Date().toISOString()).order('starts_at').limit(3)]);v.innerHTML=`<div class="card hero-card"><div class="small muted">Բարի օր</div><h2 style="font-size:clamp(27px,4vw,42px);margin:.2rem 0">${esc(st.profile.first_name)}, պատրաստ ե՞ս այսօրվա դասերին։</h2><p class="muted">Ամենակարևոր տեղեկությունը՝ մեկ տեղում։</p></div><div class="grid g3" style="margin-top:14px"><div class="card"><div class="small muted">Մոտակա տնային</div><div class="stat">${h.data?.length||0}</div></div><div class="card"><div class="small muted">Չկարդացված</div><div class="stat">${n.data?.length||0}</div></div><div class="card"><div class="small muted">Միջոցառումներ</div><div class="stat">${e.data?.length||0}</div></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><h3>Մոտակա տնայիններ</h3>${hwList(h.data||[])}</div><div class="card"><h3>Հայտարարություններ</h3>${(a.data||[]).length?`<div class="list">${a.data.map(x=>`<div class="item"><div><div class="title">${x.is_pinned?'📌 ':''}${esc(x.title)}</div><div class="small muted">${esc(x.body).slice(0,130)}</div></div>${x.is_important?'<span class="badge warn">Կարևոր</span>':''}</div>`).join('')}</div>`:'<div class="empty">Դեռ չկան</div>'}</div></div>`}
const hwList=a=>a.length?`<div class="list">${a.map(x=>`<div class="item"><div><div class="title">${esc(x.title)}</div><div class="small muted">${esc(x.subject?.name||'Առարկա')} · ${fmt(x.due_at)}</div></div><span class="badge">${esc(x.subject?.short_name||'ԴԶ')}</span></div>`).join('')}</div>`:'<div class="empty">Մոտակա տնային չկա 🎉</div>';
async function schedule(v){const r=await sb.from('schedule_entries').select('*,subject:subjects(name,short_name)').order('weekday').order('lesson_number');if(r.error)throw r.error;const d=['','Երկուշաբթի','Երեքշաբթի','Չորեքշաբթի','Հինգշաբթի','Ուրբաթ'];v.innerHTML=`<div class="grid g2">${[1,2,3,4,5].map(i=>`<div class="card"><h3>${d[i]}</h3><div class="list">${r.data.filter(x=>x.weekday===i).map(x=>`<div class="item"><div><div class="title">${x.lesson_number}. ${esc(x.subject?.name||'Առարկա')}</div><div class="small muted">${esc(x.start_time||'')}–${esc(x.end_time||'')} ${x.room?'· '+esc(x.room):''}</div></div></div>`).join('')||'<div class="empty">Դասեր նշված չեն</div>'}</div></div>`).join('')}</div>`}
async function homework(v){const [h,c]=await Promise.all([sb.from('homework').select('*,subject:subjects(name,short_name)').order('due_at'),sb.from('homework_completion').select('homework_id').eq('student_id',st.profile.id)]);if(h.error)throw h.error;const done=new Set((c.data||[]).map(x=>x.homework_id));v.innerHTML=`<div class="grid g2">${(h.data||[]).map(x=>`<div class="card"><div class="section-actions"><span class="badge">${esc(x.subject?.name||'Առարկա')}</span>${done.has(x.id)?'<span class="badge good">Արված է</span>':''}</div><h3>${esc(x.title)}</h3><p class="muted">${esc(x.description||'')}</p><div class="small muted">Վերջնաժամկետ՝ ${fmt(x.due_at)}</div><button class="btn ${done.has(x.id)?'':'primary'}" data-hw="${x.id}" data-done="${done.has(x.id)}" style="margin-top:10px">${done.has(x.id)?'Չեղարկել':'Նշել արված'}</button></div>`).join('')||'<div class="empty">Տնայիններ չկան</div>'}</div>`;$$('[data-hw]').forEach(b=>b.onclick=async()=>{busy(b,1);b.dataset.done==='true'?await sb.from('homework_completion').delete().eq('homework_id',b.dataset.hw).eq('student_id',st.profile.id):await sb.from('homework_completion').insert({homework_id:b.dataset.hw,student_id:st.profile.id,completed_at:new Date().toISOString()});homework(v)})}
async function announcements(v){const r=await sb.from('announcements').select('*,author:profiles(first_name,last_name)').order('is_pinned',{ascending:false}).order('created_at',{ascending:false});if(r.error)throw r.error;v.innerHTML=`<div class="list">${(r.data||[]).map(x=>`<article class="card"><div class="section-actions">${x.is_pinned?'<span class="badge">📌 Ամրացված</span>':''}${x.is_important?'<span class="badge warn">Կարևոր</span>':''}</div><h3>${esc(x.title)}</h3><p>${esc(x.body).replace(/\n/g,'<br>')}</p><div class="small muted">${esc(x.author?.first_name||'')} ${esc(x.author?.last_name||'')} · ${fmt(x.created_at)}</div></article>`).join('')||'<div class="empty">Հայտարարություններ չկան</div>'}</div>`}
async function board(v){const r=await sb.from('board_posts').select('*,author:profiles(first_name,last_name,username)').order('created_at',{ascending:false});if(r.error)throw r.error;v.innerHTML=`<div class="section-actions"><button id="post" class="btn primary">＋ Նոր գրառում</button></div><div class="grid g2">${(r.data||[]).map(x=>`<article class="card"><div class="small muted">${esc(x.author?.first_name||'')} ${esc(x.author?.last_name||'')} · ${fmt(x.created_at)}</div><h3>${esc(x.title)}</h3><p>${esc(x.body||'').replace(/\n/g,'<br>')}</p></article>`).join('')||'<div class="empty">Տախտակը դատարկ է</div>'}</div>`;$('#post').onclick=()=>modal('Նոր գրառում',`<form id="pf"><div class="field"><label>Վերնագիր</label><input name="title" required></div><div class="field"><label>Տեքստ</label><textarea name="body" required></textarea></div><button class="btn primary wide">Հրապարակել</button></form>`,()=>{$('#pf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.from('board_posts').insert({title:f.get('title'),body:f.get('body'),author_id:st.profile.id});if(r.error)return toast(r.error.message,'err');closeModal();board(v)}})}
async function chat(v){cleanup();const revision=chatRevision;const r=await sb.from('conversations').select('*').order('updated_at',{ascending:false});if(revision!==chatRevision||!v.isConnected||st.view!=='chat')return;if(r.error)throw r.error;const list=r.data||[];st.conv=list.find(x=>x.id===st.conv)?.id||list.find(x=>x.type==='CLASS')?.id||list[0]?.id||null;v.innerHTML=`<div class="chat"><aside class="chat-list"><div class="section-actions"><b>Զրույցներ</b><button id="direct" class="btn">＋</button></div>${list.map(x=>`<div class="conv ${x.id===st.conv?'active':''}" data-conv="${x.id}"><b>${x.type==='CLASS'?'🏫 Դասարանի չատ':x.type==='DIRECT'?'👤 Անձնական':'👥 '+esc(x.title||'Խումբ')}</b><div class="small muted">${esc(x.type)}</div></div>`).join('')||'<div class="empty">Չատ չկա</div>'}</aside><section class="chat-room"><div id="messages" class="messages"></div><form id="compose" class="compose"><input name="body" placeholder="Հաղորդագրություն…" ${st.conv?'':'disabled'}><button class="btn primary" ${st.conv?'':'disabled'}>Ուղարկել</button></form></section></div>`;$$('[data-conv]').forEach(x=>x.onclick=()=>{st.conv=x.dataset.conv;chat(v)});$('#direct').onclick=()=>direct(v);if(st.conv)mountChat(st.conv,st.profile.id)}
async function direct(v){const r=await sb.from('profiles').select('id,first_name,last_name,username').eq('is_active',true).neq('id',st.profile.id).order('first_name');modal('Նոր անձնական զրույց',`<div class="list">${(r.data||[]).map(p=>`<button class="btn" data-user="${p.id}">${esc(p.first_name)} ${esc(p.last_name)} · @${esc(p.username)}</button>`).join('')||'<div class="empty">Մյուս օգտատերեր չկան</div>'}</div>`,()=>{$$('[data-user]').forEach(b=>b.onclick=async()=>{const r=await sb.rpc('create_direct_conversation',{p_other_user:b.dataset.user});if(r.error||!r.data)return toast('Չհաջողվեց ստեղծել զրույցը','err');st.conv=r.data;closeModal();chat(v)})})}
async function polls(v){const r=await sb.from('polls').select('*,options:poll_options(*)').order('created_at',{ascending:false});if(r.error)throw r.error;v.innerHTML=`<div class="grid g2">${(r.data||[]).map(p=>`<form class="card poll" data-id="${p.id}"><span class="badge">${p.choice_mode==='SINGLE'?'Մեկ ընտրություն':'Մի քանի ընտրություն'}</span><h3>${esc(p.question)}</h3>${(p.options||[]).sort((a,b)=>a.position-b.position).map(o=>`<label style="display:flex;gap:8px;align-items:center;padding:8px 0"><input style="width:auto" type="${p.choice_mode==='SINGLE'?'radio':'checkbox'}" name="o" value="${o.id}">${esc(o.label)}</label>`).join('')}<button class="btn primary">Քվեարկել</button><button type="button" class="btn" data-results="${p.id}">Արդյունքներ</button><div id="r-${p.id}" class="small muted"></div></form>`).join('')||'<div class="empty">Հարցումներ չկան</div>'}</div>`;$$('.poll').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const ids=[...f.querySelectorAll('input:checked')].map(x=>x.value);if(!ids.length)return toast('Ընտրիր տարբերակ','err');const r=await sb.rpc('submit_poll_vote',{p_poll_id:f.dataset.id,p_option_ids:ids});r.error||!r.data?toast('Քվեարկությունը չհաջողվեց','err'):toast('Ձայնը գրանցվել է','ok')});$$('[data-results]').forEach(b=>b.onclick=async()=>{const r=await sb.rpc('get_poll_results',{p_poll_id:b.dataset.results}),x=$(`#r-${b.dataset.results}`);x.textContent=r.error?'Արդյունքները դեռ հասանելի չեն':`Ընդհանուր ձայներ՝ ${(r.data||[]).reduce((s,i)=>s+Number(i.vote_count),0)}`})}
async function files(v){const r=await sb.from('class_files').select('*,subject:subjects(name)').order('created_at',{ascending:false});if(r.error)throw r.error;v.innerHTML=`<div class="section-actions"><button id="upload" class="btn primary">⬆ Վերբեռնել</button></div><div class="list">${(r.data||[]).map(x=>`<div class="item"><div><div class="title">${esc(x.title)}</div><div class="small muted">${esc(x.original_name)} · ${esc(x.subject?.name||'Ընդհանուր')}</div></div><button class="btn" data-file="${esc(x.storage_path)}">Բացել</button></div>`).join('')||'<div class="empty">Ֆայլեր չկան</div>'}</div>`;$$('[data-file]').forEach(b=>b.onclick=async()=>{const r=await sb.storage.from('class-files').createSignedUrl(b.dataset.file,60);r.error?toast(r.error.message,'err'):window.open(r.data.signedUrl,'_blank','noopener')});$('#upload').onclick=()=>upload(v)}
function upload(v){modal('Վերբեռնել ֆայլ',`<form id="uf"><div class="field"><label>Վերնագիր</label><input name="title" required></div><div class="field"><label>Առարկա</label><select name="subject"><option value="">Ընդհանուր</option>${st.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Ֆայլ</label><input name="file" type="file" required></div><button class="btn primary wide">Վերբեռնել</button></form>`,()=>{$('#uf').onsubmit=async e=>{e.preventDefault();const b=e.submitter,f=new FormData(e.currentTarget),file=f.get('file'),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${st.profile.id}/${crypto.randomUUID()}-${safe}`;busy(b,1);let r=await sb.storage.from('class-files').upload(path,file,{contentType:file.type||'application/octet-stream'});if(!r.error)r=await sb.from('class_files').insert({title:f.get('title'),subject_id:f.get('subject')||null,storage_path:path,original_name:file.name,mime_type:file.type||null,size_bytes:file.size,uploader_id:st.profile.id});busy(b,0);if(r.error)return toast(r.error.message,'err');closeModal();files(v)}})}
async function classmates(v){const r=await sb.from('profiles').select('id,first_name,last_name,username,role,bio').eq('is_active',true).order('first_name');if(r.error)throw r.error;v.innerHTML=`<div class="grid g3">${(r.data||[]).map(p=>`<div class="card"><div class="user"><div class="avatar">${esc(initials(p))}</div><div><h3 style="margin:0">${esc(p.first_name)} ${esc(p.last_name)}</h3><div class="small muted">@${esc(p.username)}</div></div></div><p class="muted">${esc(p.bio||'')}</p><span class="badge">${esc(roleName(p.role))}</span></div>`).join('')}</div>`}
async function notifications(v){const r=await sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;v.innerHTML=`<div class="section-actions"><button id="readall" class="btn">Բոլորը կարդացված</button></div><div class="list">${(r.data||[]).map(n=>`<div class="item"><div><div class="title">${n.read_at?'':'● '}${esc(n.title)}</div><div class="small muted">${esc(n.body||'')} · ${fmt(n.created_at)}</div></div></div>`).join('')||'<div class="empty">Ծանուցումներ չկան</div>'}</div>`;$('#readall').onclick=async()=>{await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',st.profile.id).is('read_at',null);notifications(v)}}
async function profile(v){const p=st.profile;v.innerHTML=`<div class="grid g2"><div class="card"><div class="user"><div class="avatar" style="width:64px;height:64px">${esc(initials(p))}</div><div><h2 style="margin:0">${esc(p.first_name)} ${esc(p.last_name)}</h2><div class="muted">@${esc(p.username)}</div></div></div><p><span class="badge">${esc(roleName(p.role))}</span></p></div><div class="card"><h3>Խմբագրել</h3><form id="pr"><div class="field"><label>Անուն</label><input name="first" value="${esc(p.first_name)}" required></div><div class="field"><label>Ազգանուն</label><input name="last" value="${esc(p.last_name)}" required></div><div class="field"><label>Username</label><input name="username" value="${esc(p.username)}" required></div><div class="field"><label>Իմ մասին</label><textarea name="bio">${esc(p.bio||'')}</textarea></div><button class="btn primary">Պահպանել</button></form></div></div>`;$('#pr').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.from('profiles').update({first_name:f.get('first'),last_name:f.get('last'),username:f.get('username'),bio:f.get('bio')||null}).eq('id',p.id);r.error?toast(r.error.message,'err'):(toast('Պահպանվեց','ok'),identity())}}
async function adminView(v){if(!admin())return v.innerHTML='<div class="empty">Մուտքը թույլատրված չէ</div>';v.innerHTML=`<div class="grid g2"><div class="card"><h3>Նոր հայտարարություն</h3><form id="af"><div class="field"><label>Վերնագիր</label><input name="title" required></div><div class="field"><label>Տեքստ</label><textarea name="body" required></textarea></div><label><input style="width:auto" type="checkbox" name="important"> Կարևոր</label><br><label><input style="width:auto" type="checkbox" name="pinned"> Ամրացված</label><br><br><button class="btn primary">Հրապարակել</button></form></div><div class="card"><h3>Նոր տնային</h3><form id="hf"><div class="field"><label>Առարկա</label><select name="subject">${st.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Վերնագիր</label><input name="title" required></div><div class="field"><label>Նկարագրություն</label><textarea name="description"></textarea></div><div class="field"><label>Վերջնաժամկետ</label><input name="due" type="datetime-local" required></div><button class="btn primary">Ավելացնել</button></form></div></div>`;$('#af').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.from('announcements').insert({title:f.get('title'),body:f.get('body'),is_important:f.get('important')==='on',is_pinned:f.get('pinned')==='on',author_id:st.profile.id});r.error?toast(r.error.message,'err'):(e.currentTarget.reset(),toast('Հրապարակվեց','ok'))};$('#hf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.from('homework').insert({subject_id:f.get('subject'),title:f.get('title'),description:f.get('description')||null,due_at:new Date(f.get('due')).toISOString(),created_by:st.profile.id});r.error?toast(r.error.message,'err'):(e.currentTarget.reset(),toast('Ավելացվեց','ok'))}}
async function superView(v){if(!superAdmin())return v.innerHTML='<div class="empty">Միայն Super Admin</div>';const r=await sb.from('profiles').select('id,first_name,last_name,username,role,is_active').order('first_name');if(r.error)throw r.error;v.innerHTML=`<div class="card"><div class="section-actions"><button id="invite" class="btn primary">Փոխել invite code</button></div><div class="table"><table><thead><tr><th>Անուն</th><th>Username</th><th>Role</th><th>Կարգավիճակ</th><th></th></tr></thead><tbody>${(r.data||[]).map(p=>`<tr><td>${esc(p.first_name)} ${esc(p.last_name)}</td><td>@${esc(p.username)}</td><td><select data-role="${p.id}" ${p.id===st.profile.id?'disabled':''}><option ${p.role==='STUDENT'?'selected':''}>STUDENT</option><option ${p.role==='ADMIN'?'selected':''}>ADMIN</option><option ${p.role==='SUPER_ADMIN'?'selected':''}>SUPER_ADMIN</option></select></td><td>${p.is_active?'<span class="badge good">Ակտիվ</span>':'<span class="badge warn">Արգելափակված</span>'}</td><td><button class="btn ${p.is_active?'bad':'good'}" data-active="${p.id}" data-state="${p.is_active}" ${p.id===st.profile.id?'disabled':''}>${p.is_active?'Արգելափակել':'Ակտիվացնել'}</button></td></tr>`).join('')}</tbody></table></div></div>`;$$('[data-role]').forEach(x=>x.onchange=async()=>{const r=await sb.rpc('super_admin_set_user_role',{p_user_id:x.dataset.role,p_role:x.value});r.error||!r.data?toast('Role-ը չփոխվեց','err'):toast('Role-ը փոխվեց','ok')});$$('[data-active]').forEach(x=>x.onclick=async()=>{const r=await sb.rpc('super_admin_set_user_active',{p_user_id:x.dataset.active,p_active:x.dataset.state!=='true'});r.error||!r.data?toast('Կարգավիճակը չփոխվեց','err'):superView(v)});$('#invite').onclick=()=>modal('Նոր invite code',`<form id="if"><div class="field"><label>Նոր կոդ</label><input name="code" minlength="8" required></div><button class="btn primary wide">Պահպանել</button></form>`,()=>{$('#if').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.rpc('rotate_class_invite',{p_new_code:f.get('code')});r.error||!r.data?toast('Չհաջողվեց','err'):(closeModal(),toast('Invite code-ը փոխվեց','ok'))}})}
function modal(t,h,ready){closeModal();const e=document.createElement('div');e.className='modal-wrap';e.id='modal';e.innerHTML=`<div class="modal"><div class="top"><h2>${esc(t)}</h2><button id="x" class="btn">✕</button></div>${h}</div>`;document.body.append(e);$('#x').onclick=closeModal;e.onclick=x=>{if(x.target===e)closeModal()};ready?.()} function closeModal(){$('#modal')?.remove()} function cleanup(){chatRevision++;stopChat();if(st.channel){sb.removeChannel(st.channel);st.channel=null}}
boot().catch(e=>fatal('Պորտալը չի գործարկվում',e.message||String(e)));
