import { sb } from '../lib/supabase.js';
import { el,esc,fmt,toast } from '../lib/dom.js';

const page=(eyebrow,title,body,subtitle='')=>el(`<main class="page"><header class="page-header"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${subtitle?`<p class="subtle">${subtitle}</p>`:''}</div></header>${body}</main>`);

export async function renderSchedule(){
  const r=await sb.from('schedule_entries').select('*,subject:subjects(name,short_name,icon)').order('weekday').order('lesson_number');if(r.error)throw r.error;
  const days=['','Երկուշաբթի','Երեքշաբթի','Չորեքշաբթի','Հինգշաբթի','Ուրբաթ'];
  return page('Schedule','Դասացուցակ',`<section class="grid grid-2">${[1,2,3,4,5].map(day=>`<article class="card"><h2>${days[day]}</h2><div class="stack">${(r.data||[]).filter(x=>x.weekday===day).map(x=>`<div class="list-item"><div><strong>${x.subject?.icon?esc(x.subject.icon)+' ':''}${esc(x.subject?.name||'Առարկա')}</strong><div class="subtle" style="font-size:.8rem;margin-top:4px">${esc((x.start_time||'').slice(0,5))}–${esc((x.end_time||'').slice(0,5))}${x.room?` · ${esc(x.room)}`:''}</div></div><span class="pill">${x.lesson_number}</span></div>`).join('')||'<div class="empty">Դաս չկա</div>'}</div></article>`).join('')}</section>`);
}

export async function renderHomework({profile}){
  const [h,c]=await Promise.all([sb.from('homework').select('*,subject:subjects(name,short_name,icon)').order('due_at'),sb.from('homework_completion').select('homework_id').eq('student_id',profile.id)]);if(h.error)throw h.error;const done=new Set((c.data||[]).map(x=>x.homework_id));
  const node=page('Homework','Տնայիններ',`<section class="grid grid-2">${(h.data||[]).map(x=>`<article class="card"><div class="row between"><span class="subject-chip">${x.subject?.icon?esc(x.subject.icon)+' ':''}${esc(x.subject?.short_name||x.subject?.name||'ԴԶ')}</span>${done.has(x.id)?'<span class="pill" style="color:var(--success)">Արված է</span>':''}</div><h3 style="margin:14px 0 7px">${esc(x.title)}</h3><p class="subtle">${esc(x.description||'')}</p><div class="subtle" style="font-size:.8rem">${fmt(x.due_at)}</div></article>`).join('')||'<div class="empty">Տնայիններ չկան</div>'}</section>`);
  return node;
}

export async function renderAnnouncements(){const r=await sb.from('announcements').select('*,author:profiles(first_name,last_name)').order('is_pinned',{ascending:false}).order('created_at',{ascending:false});if(r.error)throw r.error;return page('News','Հայտարարություններ',`<section class="stack">${(r.data||[]).map(x=>`<article class="card"><div class="row between wrap"><div class="eyebrow">${esc(x.author?.first_name||'')} ${esc(x.author?.last_name||'')}</div><div class="row">${x.is_pinned?'<span class="pill">📌 Ամրացված</span>':''}${x.is_important?'<span class="pill" style="color:var(--warning)">Կարևոր</span>':''}</div></div><h2 style="margin-top:12px">${esc(x.title)}</h2><p>${esc(x.body||'').replace(/\n/g,'<br>')}</p><div class="subtle" style="font-size:.8rem">${fmt(x.created_at)}</div></article>`).join('')||'<div class="empty">Հայտարարություն չկա</div>'}</section>`)}

export async function renderBoard({profile}){const r=await sb.from('board_posts').select('*,author:profiles(first_name,last_name,username)').order('created_at',{ascending:false});if(r.error)throw r.error;const node=page('Class Board','Տախտակ',`<section class="row between wrap" style="margin-bottom:16px"><p class="subtle" style="margin:0">Դասարանի ընդհանուր գրառումներ</p><button class="button primary" data-new-post>＋ Նոր գրառում</button></section><section class="grid grid-2">${(r.data||[]).map(x=>`<article class="card"><div class="eyebrow">@${esc(x.author?.username||'user')} · ${fmt(x.created_at)}</div><h3 style="margin:10px 0 6px">${esc(x.title)}</h3><p>${esc(x.body||'').replace(/\n/g,'<br>')}</p></article>`).join('')||'<div class="empty">Տախտակը դատարկ է</div>'}</section>`);node.querySelector('[data-new-post]').addEventListener('click',async()=>{const title=prompt('Վերնագիր');if(!title)return;const body=prompt('Տեքստ');if(!body)return;const x=await sb.from('board_posts').insert({title,body,author_id:profile.id});x.error?toast(x.error.message,'err'):toast('Հրապարակվեց','ok')});return node}

export async function renderPolls(){const r=await sb.from('polls').select('*,options:poll_options(*)').order('created_at',{ascending:false});if(r.error)throw r.error;const node=page('Polls','Հարցումներ',`<section class="grid grid-2">${(r.data||[]).map(p=>`<form class="card" data-poll="${p.id}"><span class="pill">${p.choice_mode==='SINGLE'?'Մեկ ընտրություն':'Մի քանի ընտրություն'}</span><h2 style="margin-top:13px">${esc(p.question)}</h2><div class="stack">${(p.options||[]).sort((a,b)=>a.position-b.position).map(o=>`<label class="list-item" style="justify-content:flex-start"><input style="width:auto" type="${p.choice_mode==='SINGLE'?'radio':'checkbox'}" name="option" value="${o.id}">${esc(o.label)}</label>`).join('')}</div><button class="button primary" style="margin-top:14px">Քվեարկել</button></form>`).join('')||'<div class="empty">Հարցումներ չկան</div>'}</section>`);node.querySelectorAll('[data-poll]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const ids=[...form.querySelectorAll('input:checked')].map(x=>x.value);if(!ids.length)return toast('Ընտրիր տարբերակ','err');const r=await sb.rpc('submit_poll_vote',{p_poll_id:form.dataset.poll,p_option_ids:ids});r.error||!r.data?toast('Քվեարկությունը չհաջողվեց','err'):toast('Ձայնը գրանցվեց','ok')}));return node}

export async function renderFiles(){const r=await sb.from('class_files').select('*,subject:subjects(name)').order('created_at',{ascending:false});if(r.error)throw r.error;const node=page('Files','Ֆայլեր',`<section class="stack">${(r.data||[]).map(x=>`<div class="list-item"><div><strong>${esc(x.title)}</strong><div class="subtle" style="font-size:.8rem;margin-top:4px">${esc(x.original_name)} · ${esc(x.subject?.name||'Ընդհանուր')}</div></div><button class="button ghost" data-open-file="${esc(x.storage_path)}">Բացել</button></div>`).join('')||'<div class="empty">Ֆայլեր չկան</div>'}</section>`);node.querySelectorAll('[data-open-file]').forEach(b=>b.addEventListener('click',async()=>{const r=await sb.storage.from('class-files').createSignedUrl(b.dataset.openFile,60);r.error?toast(r.error.message,'err'):window.open(r.data.signedUrl,'_blank','noopener')}));return node}

export async function renderClassmates(){const r=await sb.from('profiles').select('id,first_name,last_name,username,role,bio').eq('is_active',true).order('first_name');if(r.error)throw r.error;return page('Class','Դասընկերներ',`<section class="grid grid-3">${(r.data||[]).map(p=>`<article class="card"><div class="row"><div class="avatar">${esc((p.first_name?.[0]||'')+(p.last_name?.[0]||''))}</div><div><strong>${esc(p.first_name)} ${esc(p.last_name)}</strong><div class="subtle" style="font-size:.8rem">@${esc(p.username)}</div></div></div><p class="subtle" style="margin:14px 0 0">${esc(p.bio||'')}</p><span class="pill" style="margin-top:12px">${esc(p.role)}</span></article>`).join('')}</section>`)}

export async function renderNotifications({profile}){const r=await sb.from('notifications').select('*').eq('user_id',profile.id).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;const node=page('Notifications','Ծանուցումներ',`<section class="row between wrap" style="margin-bottom:16px"><p class="subtle" style="margin:0">Քո վերջին թարմացումները</p><button class="button ghost" data-read-all>Բոլորը կարդացված</button></section><section class="stack">${(r.data||[]).map(n=>`<div class="list-item"><div><strong>${n.read_at?'':'● '}${esc(n.title)}</strong><div class="subtle" style="font-size:.8rem;margin-top:4px">${esc(n.body||'')} · ${fmt(n.created_at)}</div></div></div>`).join('')||'<div class="empty">Ծանուցումներ չկան</div>'}</section>`);node.querySelector('[data-read-all]').addEventListener('click',async()=>{const x=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',profile.id).is('read_at',null);x.error?toast(x.error.message,'err'):toast('Պատրաստ է','ok')});return node}

export async function renderProfile({profile,onRefresh}){const node=page('Account','Պրոֆիլ',`<section class="grid grid-2"><article class="card"><div class="row"><div class="avatar" style="width:68px;height:68px;font-size:1.25rem">${esc((profile.first_name?.[0]||'')+(profile.last_name?.[0]||''))}</div><div><h2 style="margin:0">${esc(profile.first_name)} ${esc(profile.last_name)}</h2><div class="subtle">@${esc(profile.username)}</div></div></div><span class="pill" style="margin-top:18px">${esc(profile.role)}</span></article><article class="card"><h2>Խմբագրել</h2><form data-profile><div class="field"><label>Անուն</label><input class="input" name="first" value="${esc(profile.first_name)}" required></div><div class="field"><label>Ազգանուն</label><input class="input" name="last" value="${esc(profile.last_name)}" required></div><div class="field"><label>Username</label><input class="input" name="username" value="${esc(profile.username)}" minlength="3" maxlength="32" required></div><div class="field"><label>Իմ մասին</label><textarea class="textarea" name="bio">${esc(profile.bio||'')}</textarea></div><button class="button primary">Պահպանել</button></form></article></section>`);node.querySelector('[data-profile]').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const x=await sb.rpc('update_my_profile_safe',{p_first_name:f.get('first'),p_last_name:f.get('last'),p_username:f.get('username'),p_bio:f.get('bio')||null});if(x.error||x.data!==true)return toast(x.error?.message||'Չհաջողվեց պահպանել','err');toast('Պահպանվեց','ok');onRefresh?.()});return node}
